// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wboNivZUXwuALwWQq1HqWe
// Component: hWxUsOX3v_FW

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseCheckbox } from "@plasmicpkgs/react-aria/skinny/registerCheckbox";

import {
  ThemeValue,
  useTheme
} from "../17_sds_foundation_global/PlasmicGlobalVariant__Theme"; // plasmic-import: yBTVTgAz2Co9/globalVariant
import { useScreenVariants as useScreenVariantsohEUf6Jd0EV8 } from "../17_sds_foundation_global/PlasmicGlobalVariant__Screen"; // plasmic-import: OhEUf6Jd0eV8/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_17_sds_foundation_global_css from "../17_sds_foundation_global/plasmic.module.css"; // plasmic-import: 3BHMWCYAenCmWb8ThbnzeF/projectcss
import plasmic_17_sds_foundation_system_css from "../17_sds_foundation_system/plasmic.module.css"; // plasmic-import: dNqcW7FYVqnkjtbdVGjyS8/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wboNivZUXwuALwWQq1HqWe/projectcss
import sty from "./PlasmicUnusedComponentsCheckbox.module.css"; // plasmic-import: hWxUsOX3v_FW/css

import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: RBiRjhO0DzbV/icon
import MinusIcon from "./icons/PlasmicIcon__Minus"; // plasmic-import: 662tEaBUHtSS/icon

createPlasmicElementProxy;

export type PlasmicUnusedComponentsCheckbox__VariantMembers = {};
export type PlasmicUnusedComponentsCheckbox__VariantsArgs = {};
type VariantPropType = keyof PlasmicUnusedComponentsCheckbox__VariantsArgs;
export const PlasmicUnusedComponentsCheckbox__VariantProps =
  new Array<VariantPropType>();

export type PlasmicUnusedComponentsCheckbox__ArgsType = {
  value?: string;
  defaultSelected?: boolean;
  autoFocus?: boolean;
  ariaLabel?: string;
  onChange?: (val: boolean) => void;
  label?: React.ReactNode;
};
type ArgPropType = keyof PlasmicUnusedComponentsCheckbox__ArgsType;
export const PlasmicUnusedComponentsCheckbox__ArgProps = new Array<ArgPropType>(
  "value",
  "defaultSelected",
  "autoFocus",
  "ariaLabel",
  "onChange",
  "label"
);

export type PlasmicUnusedComponentsCheckbox__OverridesType = {
  ariaCheckbox?: Flex__<typeof BaseCheckbox>;
  checkboxStack?: Flex__<"div">;
};

export interface DefaultUnusedComponentsCheckboxProps {
  value?: string;
  defaultSelected?: boolean;
  autoFocus?: boolean;
  ariaLabel?: string;
  onChange?: (val: boolean) => void;
  label?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUnusedComponentsCheckbox__RenderFunc(props: {
  variants: PlasmicUnusedComponentsCheckbox__VariantsArgs;
  args: PlasmicUnusedComponentsCheckbox__ArgsType;
  overrides: PlasmicUnusedComponentsCheckbox__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          defaultSelected: false,
          autoFocus: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ariaCheckbox.isSelected",
        type: "readonly",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props["defaultSelected"],

        onChangeProp: "onChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    theme: useTheme(),
    screen: useScreenVariantsohEUf6Jd0EV8()
  });

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    hovered: false,
    pressed: false,
    focused: false,
    focusVisible: false,
    indeterminate: false,
    disabled: false,
    selected: false,
    readonly: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseCheckbox
      data-plasmic-name={"ariaCheckbox"}
      data-plasmic-override={overrides.ariaCheckbox}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      autoFocus={args.autoFocus}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_17_sds_foundation_global_css.plasmic_tokens,
        plasmic_17_sds_foundation_system_css.plasmic_tokens,
        sty.ariaCheckbox,
        {
          [plasmic_17_sds_foundation_global_css.global_theme_darkGrayscale]:
            hasVariant(globalVariants, "theme", "darkGrayscale"),
          [plasmic_17_sds_foundation_global_css.global_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [plasmic_17_sds_foundation_global_css.global_theme_grayscale]:
            hasVariant(globalVariants, "theme", "grayscale")
        }
      )}
      defaultSelected={args.defaultSelected}
      isDisabled={$ccVariants["disabled"] ? true : undefined}
      isIndeterminate={$ccVariants["indeterminate"] ? true : undefined}
      isReadOnly={$ccVariants["readonly"] ? true : undefined}
      isSelected={generateStateValueProp($state, [
        "ariaCheckbox",
        "isSelected"
      ])}
      onChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["ariaCheckbox", "isSelected"]).apply(
          null,
          eventArgs
        );
      }}
      plasmicUpdateVariant={updateVariant}
      value={args.value}
    >
      <div
        data-plasmic-name={"checkboxStack"}
        data-plasmic-override={overrides.checkboxStack}
        className={classNames(projectcss.all, sty.checkboxStack)}
      >
        <CheckIcon
          className={classNames(projectcss.all, sty.svg__uio9L)}
          role={"img"}
        />

        <MinusIcon
          className={classNames(projectcss.all, sty.svg__eTv2E)}
          role={"img"}
        />
      </div>
      {renderPlasmicSlot({
        defaultContents: "Option",
        value: args.label
      })}
    </BaseCheckbox>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  ariaCheckbox: ["ariaCheckbox", "checkboxStack"],
  checkboxStack: ["checkboxStack"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  ariaCheckbox: typeof BaseCheckbox;
  checkboxStack: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUnusedComponentsCheckbox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUnusedComponentsCheckbox__VariantsArgs;
    args?: PlasmicUnusedComponentsCheckbox__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUnusedComponentsCheckbox__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicUnusedComponentsCheckbox__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUnusedComponentsCheckbox__ArgProps,
          internalVariantPropNames:
            PlasmicUnusedComponentsCheckbox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUnusedComponentsCheckbox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaCheckbox") {
    func.displayName = "PlasmicUnusedComponentsCheckbox";
  } else {
    func.displayName = `PlasmicUnusedComponentsCheckbox.${nodeName}`;
  }
  return func;
}

export const PlasmicUnusedComponentsCheckbox = Object.assign(
  // Top-level PlasmicUnusedComponentsCheckbox renders the root element
  makeNodeComponent("ariaCheckbox"),
  {
    // Helper components rendering sub-elements
    checkboxStack: makeNodeComponent("checkboxStack"),

    // Metadata about props expected for PlasmicUnusedComponentsCheckbox
    internalVariantProps: PlasmicUnusedComponentsCheckbox__VariantProps,
    internalArgProps: PlasmicUnusedComponentsCheckbox__ArgProps
  }
);

export default PlasmicUnusedComponentsCheckbox;
/* prettier-ignore-end */
