// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wboNivZUXwuALwWQq1HqWe
// Component: owTExFnZGR7G

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import LayoutPageLayout from "../../LayoutPageLayout"; // plasmic-import: Zd-Ayv7Gl3LR/component
import { CmsQueryRepeater } from "@plasmicpkgs/plasmic-cms";
import { CmsRowImage } from "@plasmicpkgs/plasmic-cms";
import { CmsRowField } from "@plasmicpkgs/plasmic-cms";

import {
  ThemeValue,
  useTheme
} from "../17_sds_foundation_global/PlasmicGlobalVariant__Theme"; // plasmic-import: yBTVTgAz2Co9/globalVariant
import { useScreenVariants as useScreenVariantsohEUf6Jd0EV8 } from "../17_sds_foundation_global/PlasmicGlobalVariant__Screen"; // plasmic-import: OhEUf6Jd0eV8/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_17_sds_foundation_global_css from "../17_sds_foundation_global/plasmic.module.css"; // plasmic-import: 3BHMWCYAenCmWb8ThbnzeF/projectcss
import plasmic_17_sds_foundation_system_css from "../17_sds_foundation_system/plasmic.module.css"; // plasmic-import: dNqcW7FYVqnkjtbdVGjyS8/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wboNivZUXwuALwWQq1HqWe/projectcss
import sty from "./PlasmicCatalogueLearning.module.css"; // plasmic-import: owTExFnZGR7G/css

createPlasmicElementProxy;

export type PlasmicCatalogueLearning__VariantMembers = {};
export type PlasmicCatalogueLearning__VariantsArgs = {};
type VariantPropType = keyof PlasmicCatalogueLearning__VariantsArgs;
export const PlasmicCatalogueLearning__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCatalogueLearning__ArgsType = {};
type ArgPropType = keyof PlasmicCatalogueLearning__ArgsType;
export const PlasmicCatalogueLearning__ArgProps = new Array<ArgPropType>();

export type PlasmicCatalogueLearning__OverridesType = {
  root?: Flex__<typeof LayoutPageLayout>;
  cmsEntryImage?: Flex__<typeof CmsRowImage>;
  img?: Flex__<typeof PlasmicImg__>;
  h2?: Flex__<"h2">;
  cmsEntryField?: Flex__<typeof CmsRowField>;
};

export interface DefaultCatalogueLearningProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCatalogueLearning__RenderFunc(props: {
  variants: PlasmicCatalogueLearning__VariantsArgs;
  args: PlasmicCatalogueLearning__ArgsType;
  overrides: PlasmicCatalogueLearning__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme(),
    screen: useScreenVariantsohEUf6Jd0EV8()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <LayoutPageLayout
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
        >
          <CmsQueryRepeater
            className={classNames("__wab_instance", sty.cmsDataFetcher__fq21Q)}
            desc={false}
            emptyMessage={
              <DataCtxReader__>
                {$ctx => (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kIyLd
                    )}
                  >
                    {"No matching published entries found."}
                  </div>
                )}
              </DataCtxReader__>
            }
            filterField={"slug"}
            filterValue={(() => {
              try {
                return $ctx.params.slug;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            forceEmptyState={false}
            forceLoadingState={false}
            limit={0}
            loadingMessage={
              <DataCtxReader__>
                {$ctx => (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__za5Gc
                    )}
                  >
                    {"Loading..."}
                  </div>
                )}
              </DataCtxReader__>
            }
            noAutoRepeat={false}
            noLayout={false}
            table={"learning"}
            useDraft={false}
          >
            <DataCtxReader__>
              {$ctx => (
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bfXkx)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__biVlt)}
                  >
                    <CmsQueryRepeater
                      className={classNames(
                        "__wab_instance",
                        sty.cmsDataFetcher___4AwNl
                      )}
                      desc={false}
                      emptyMessage={
                        <DataCtxReader__>
                          {$ctx => (
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lbBKa
                              )}
                            >
                              {"No matching published entries found."}
                            </div>
                          )}
                        </DataCtxReader__>
                      }
                      filterField={"_id"}
                      filterValue={(() => {
                        try {
                          return $ctx.plasmicCmsLearningItem.data.thumbnail;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      forceEmptyState={false}
                      forceLoadingState={false}
                      limit={0}
                      loadingMessage={
                        <DataCtxReader__>
                          {$ctx => (
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__eYrj
                              )}
                            >
                              {"Loading..."}
                            </div>
                          )}
                        </DataCtxReader__>
                      }
                      noAutoRepeat={false}
                      noLayout={false}
                      table={"media"}
                      useDraft={false}
                    >
                      <DataCtxReader__>
                        {$ctx => (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___1T0Pq
                            )}
                          >
                            <CmsRowImage
                              data-plasmic-name={"cmsEntryImage"}
                              data-plasmic-override={overrides.cmsEntryImage}
                              className={classNames(
                                "__wab_instance",
                                sty.cmsEntryImage
                              )}
                              srcProp={"src"}
                              table={"media"}
                            >
                              <PlasmicImg__
                                data-plasmic-name={"img"}
                                data-plasmic-override={overrides.img}
                                alt={""}
                                className={classNames(sty.img)}
                                displayHeight={"auto"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                height={``}
                                loading={"eager"}
                                src={
                                  "https://studio.plasmic.app/static/img/placeholder-full.png"
                                }
                              />
                            </CmsRowImage>
                          </div>
                        )}
                      </DataCtxReader__>
                    </CmsQueryRepeater>
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $ctx.plasmicCmsLearningCollection[0]
                              .identifier;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "John Hammond";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </h2>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__emJkt)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jTpKi
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return (() => {
                              const date = new Date(
                                $ctx.plasmicCmsLearningItem.data.date
                              );
                              const options = {
                                year: "numeric",
                                month: "long",
                                day: "numeric"
                              };
                              return date.toLocaleDateString("en-US", options);
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__aciOv)}
                    >
                      <CmsQueryRepeater
                        className={classNames(
                          "__wab_instance",
                          sty.cmsDataFetcher___2KfW8
                        )}
                        desc={false}
                        emptyMessage={
                          <DataCtxReader__>
                            {$ctx => (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___1WGc5
                                )}
                              >
                                {"No matching published entries found."}
                              </div>
                            )}
                          </DataCtxReader__>
                        }
                        filterField={"_id"}
                        filterValue={(() => {
                          try {
                            return $ctx.plasmicCmsLearningItem.data.author;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        forceEmptyState={false}
                        forceLoadingState={false}
                        limit={0}
                        loadingMessage={
                          <DataCtxReader__>
                            {$ctx => (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__lKwzR
                                )}
                              >
                                {"Loading..."}
                              </div>
                            )}
                          </DataCtxReader__>
                        }
                        noAutoRepeat={false}
                        noLayout={false}
                        table={"author"}
                        useDraft={false}
                      >
                        <DataCtxReader__>
                          {$ctx => (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___46Ter
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___6Bu1E
                                )}
                              >
                                {"By: "}
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__tUiXt
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["goToAboutAuthorAuthor"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination: `/author/${(() => {
                                            try {
                                              return $ctx.plasmicCmsAuthorItem
                                                .data.slug;
                                            } catch (e) {
                                              if (
                                                e instanceof TypeError ||
                                                e?.plasmicType ===
                                                  "PlasmicUndefinedDataError"
                                              ) {
                                                return undefined;
                                              }
                                              throw e;
                                            }
                                          })()}`
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["goToAboutAuthorAuthor"] != null &&
                                    typeof $steps["goToAboutAuthorAuthor"] ===
                                      "object" &&
                                    typeof $steps["goToAboutAuthorAuthor"]
                                      .then === "function"
                                  ) {
                                    $steps["goToAboutAuthorAuthor"] =
                                      await $steps["goToAboutAuthorAuthor"];
                                  }
                                }}
                              >
                                <CmsRowField
                                  data-plasmic-name={"cmsEntryField"}
                                  data-plasmic-override={
                                    overrides.cmsEntryField
                                  }
                                  className={classNames(
                                    "__wab_instance",
                                    sty.cmsEntryField
                                  )}
                                  field={"name"}
                                  table={"author"}
                                  themeResetClassName={classNames(
                                    projectcss.root_reset,
                                    projectcss.root_reset_tags,
                                    projectcss.plasmic_default_styles,
                                    projectcss.plasmic_mixins,
                                    projectcss.plasmic_tokens,
                                    plasmic_17_sds_foundation_global_css.plasmic_tokens,
                                    plasmic_17_sds_foundation_system_css.plasmic_tokens,
                                    {
                                      [plasmic_17_sds_foundation_global_css.global_theme_darkGrayscale]:
                                        hasVariant(
                                          globalVariants,
                                          "theme",
                                          "darkGrayscale"
                                        ),
                                      [plasmic_17_sds_foundation_global_css.global_theme_dark]:
                                        hasVariant(
                                          globalVariants,
                                          "theme",
                                          "dark"
                                        ),
                                      [plasmic_17_sds_foundation_global_css.global_theme_grayscale]:
                                        hasVariant(
                                          globalVariants,
                                          "theme",
                                          "grayscale"
                                        )
                                    }
                                  )}
                                />
                              </Stack__>
                            </div>
                          )}
                        </DataCtxReader__>
                      </CmsQueryRepeater>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___8BAos)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zDxVr
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $ctx.plasmicCmsLearningItem.data.description;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."';
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </Stack__>
                </Stack__>
              )}
            </DataCtxReader__>
          </CmsQueryRepeater>
        </LayoutPageLayout>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "cmsEntryImage", "img", "h2", "cmsEntryField"],
  cmsEntryImage: ["cmsEntryImage", "img"],
  img: ["img"],
  h2: ["h2"],
  cmsEntryField: ["cmsEntryField"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof LayoutPageLayout;
  cmsEntryImage: typeof CmsRowImage;
  img: typeof PlasmicImg__;
  h2: "h2";
  cmsEntryField: typeof CmsRowField;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCatalogueLearning__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCatalogueLearning__VariantsArgs;
    args?: PlasmicCatalogueLearning__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCatalogueLearning__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCatalogueLearning__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCatalogueLearning__ArgProps,
          internalVariantPropNames: PlasmicCatalogueLearning__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCatalogueLearning__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCatalogueLearning";
  } else {
    func.displayName = `PlasmicCatalogueLearning.${nodeName}`;
  }
  return func;
}

export const PlasmicCatalogueLearning = Object.assign(
  // Top-level PlasmicCatalogueLearning renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cmsEntryImage: makeNodeComponent("cmsEntryImage"),
    img: makeNodeComponent("img"),
    h2: makeNodeComponent("h2"),
    cmsEntryField: makeNodeComponent("cmsEntryField"),

    // Metadata about props expected for PlasmicCatalogueLearning
    internalVariantProps: PlasmicCatalogueLearning__VariantProps,
    internalArgProps: PlasmicCatalogueLearning__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCatalogueLearning;
/* prettier-ignore-end */
