// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wboNivZUXwuALwWQq1HqWe
// Component: rBfmFgZSykn7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import LayoutPageLayout from "../../LayoutPageLayout"; // plasmic-import: Zd-Ayv7Gl3LR/component
import { CmsQueryRepeater } from "@plasmicpkgs/plasmic-cms";
import { CmsRowImage } from "@plasmicpkgs/plasmic-cms";
import BaseComponentsSocialIcons from "../../BaseComponentsSocialIcons"; // plasmic-import: fANKuPlo2Cc-/component
import ComponentsLearningLearnings from "../../ComponentsLearningLearnings"; // plasmic-import: AhUJHR7qqo47/component

import {
  ThemeValue,
  useTheme
} from "../17_sds_foundation_global/PlasmicGlobalVariant__Theme"; // plasmic-import: yBTVTgAz2Co9/globalVariant
import { useScreenVariants as useScreenVariantsohEUf6Jd0EV8 } from "../17_sds_foundation_global/PlasmicGlobalVariant__Screen"; // plasmic-import: OhEUf6Jd0eV8/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_17_sds_foundation_global_css from "../17_sds_foundation_global/plasmic.module.css"; // plasmic-import: 3BHMWCYAenCmWb8ThbnzeF/projectcss
import plasmic_17_sds_foundation_system_css from "../17_sds_foundation_system/plasmic.module.css"; // plasmic-import: dNqcW7FYVqnkjtbdVGjyS8/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wboNivZUXwuALwWQq1HqWe/projectcss
import sty from "./PlasmicAboutAuthorAuthor.module.css"; // plasmic-import: rBfmFgZSykn7/css

createPlasmicElementProxy;

export type PlasmicAboutAuthorAuthor__VariantMembers = {};
export type PlasmicAboutAuthorAuthor__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutAuthorAuthor__VariantsArgs;
export const PlasmicAboutAuthorAuthor__VariantProps =
  new Array<VariantPropType>();

export type PlasmicAboutAuthorAuthor__ArgsType = {};
type ArgPropType = keyof PlasmicAboutAuthorAuthor__ArgsType;
export const PlasmicAboutAuthorAuthor__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutAuthorAuthor__OverridesType = {
  root?: Flex__<typeof LayoutPageLayout>;
  columns?: Flex__<"div">;
  column?: Flex__<"div">;
  h1?: Flex__<"h1">;
  cmsEntryImage?: Flex__<typeof CmsRowImage>;
  img?: Flex__<typeof PlasmicImg__>;
  baseComponentsSocialIcons?: Flex__<typeof BaseComponentsSocialIcons>;
  componentsLearningLearnings?: Flex__<typeof ComponentsLearningLearnings>;
};

export interface DefaultAboutAuthorAuthorProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutAuthorAuthor__RenderFunc(props: {
  variants: PlasmicAboutAuthorAuthor__VariantsArgs;
  args: PlasmicAboutAuthorAuthor__ArgsType;
  overrides: PlasmicAboutAuthorAuthor__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme(),
    screen: useScreenVariantsohEUf6Jd0EV8()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <LayoutPageLayout
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
        >
          <CmsQueryRepeater
            className={classNames("__wab_instance", sty.cmsDataFetcher__f3OgR)}
            desc={false}
            emptyMessage={
              <DataCtxReader__>
                {$ctx => (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zgGqd
                    )}
                  >
                    {"No matching published entries found."}
                  </div>
                )}
              </DataCtxReader__>
            }
            filterField={"slug"}
            filterValue={(() => {
              try {
                return $ctx.params.slug;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            forceEmptyState={false}
            forceLoadingState={false}
            limit={0}
            loadingMessage={
              <DataCtxReader__>
                {$ctx => (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__caV1
                    )}
                  >
                    {"Loading..."}
                  </div>
                )}
              </DataCtxReader__>
            }
            noAutoRepeat={false}
            noLayout={false}
            table={"author"}
            useDraft={false}
          >
            <DataCtxReader__>
              {$ctx => (
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iIoxN)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"columns"}
                    data-plasmic-override={overrides.columns}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"column"}
                      data-plasmic-override={overrides.column}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__a0Mjc
                        )}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__v7VNo
                          )}
                        >
                          <h1
                            data-plasmic-name={"h1"}
                            data-plasmic-override={overrides.h1}
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              projectcss.__wab_text,
                              sty.h1
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $ctx.plasmicCmsAuthorItem.data.name;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "John Hammond";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </h1>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tn2Oo
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__ab3M4
                            )}
                          >
                            {"Instructor"}
                          </h3>
                        </Stack__>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__md4Je
                        )}
                      >
                        <CmsQueryRepeater
                          className={classNames(
                            "__wab_instance",
                            sty.cmsDataFetcher__m9JzE
                          )}
                          desc={false}
                          emptyMessage={
                            <DataCtxReader__>
                              {$ctx => (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__noYwD
                                  )}
                                >
                                  {"No matching published entries found."}
                                </div>
                              )}
                            </DataCtxReader__>
                          }
                          filterField={"_id"}
                          filterValue={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.pic;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          forceEmptyState={false}
                          forceLoadingState={false}
                          limit={0}
                          loadingMessage={
                            <DataCtxReader__>
                              {$ctx => (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___3J3Q
                                  )}
                                >
                                  {"Loading..."}
                                </div>
                              )}
                            </DataCtxReader__>
                          }
                          noAutoRepeat={false}
                          noLayout={false}
                          table={"media"}
                          useDraft={false}
                        >
                          <DataCtxReader__>
                            {$ctx => (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__sCoZi
                                )}
                              >
                                <CmsRowImage
                                  data-plasmic-name={"cmsEntryImage"}
                                  data-plasmic-override={
                                    overrides.cmsEntryImage
                                  }
                                  className={classNames(
                                    "__wab_instance",
                                    sty.cmsEntryImage
                                  )}
                                  srcProp={"src"}
                                  table={"media"}
                                >
                                  <PlasmicImg__
                                    data-plasmic-name={"img"}
                                    data-plasmic-override={overrides.img}
                                    alt={""}
                                    className={classNames(sty.img)}
                                    displayHeight={"auto"}
                                    displayMaxHeight={"none"}
                                    displayMaxWidth={"none"}
                                    displayMinHeight={"0"}
                                    displayMinWidth={"0"}
                                    displayWidth={"600px"}
                                    loading={"eager"}
                                    src={
                                      "https://studio.plasmic.app/static/img/placeholder-full.png"
                                    }
                                  />
                                </CmsRowImage>
                              </div>
                            )}
                          </DataCtxReader__>
                        </CmsQueryRepeater>
                        <BaseComponentsSocialIcons
                          data-plasmic-name={"baseComponentsSocialIcons"}
                          data-plasmic-override={
                            overrides.baseComponentsSocialIcons
                          }
                          blueskyUsername={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "bluesky"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "bluesky"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          className={classNames(
                            "__wab_instance",
                            sty.baseComponentsSocialIcons
                          )}
                          discordServer={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "discord"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "discord"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          facebookProfile={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account =>
                                  account["account type"] === "facebook"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "facebook"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          githubUsername={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "github"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "github"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          instagramUsername={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account =>
                                  account["account type"] === "instagram"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "instagram"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          linkedinProfile={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account =>
                                  account["account type"] === "linkedin"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "linkedin"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          mastadonUsername={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account =>
                                  account["account type"] === "mastadon"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "mastadon"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          mediumProfile={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "medium"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "medium"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          socialItem={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].map(account => account["account type"]);
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return [];
                              }
                              throw e;
                            }
                          })()}
                          spotifyPage={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "spotify"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "spotify"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          threadsUsername={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "threads"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "threads"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          twitchServer={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "twitch"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "twitch"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          xtwitterId={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(account => account["account type"] === "x")
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account => account["account type"] === "x"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          youtubeProfile={(() => {
                            try {
                              return $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                "social media accounts"
                              ].find(
                                account => account["account type"] === "youtube"
                              )
                                ? $ctx.plasmicCmsAuthorItem.data.contactInfo[
                                    "social media accounts"
                                  ].find(
                                    account =>
                                      account["account type"] === "youtube"
                                  )["account lnk"]
                                : "";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      </Stack__>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__pDlbB)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__naT6
                      )}
                    >
                      {"Bio"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__caGxW
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $ctx.plasmicCmsAuthorItem.data.bio;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."';
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gstAr)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__yNmxT
                      )}
                    >
                      {"Courses"}
                    </h3>
                    <ComponentsLearningLearnings
                      data-plasmic-name={"componentsLearningLearnings"}
                      data-plasmic-override={
                        overrides.componentsLearningLearnings
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.componentsLearningLearnings
                      )}
                      filterField={"author"}
                      filterValue={(() => {
                        try {
                          return $ctx.plasmicCmsAuthorItem.id;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      unnamedGroupOfVariants={"filtered"}
                    />
                  </Stack__>
                </Stack__>
              )}
            </DataCtxReader__>
          </CmsQueryRepeater>
        </LayoutPageLayout>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "columns",
    "column",
    "h1",
    "cmsEntryImage",
    "img",
    "baseComponentsSocialIcons",
    "componentsLearningLearnings"
  ],
  columns: [
    "columns",
    "column",
    "h1",
    "cmsEntryImage",
    "img",
    "baseComponentsSocialIcons"
  ],
  column: ["column", "h1", "cmsEntryImage", "img", "baseComponentsSocialIcons"],
  h1: ["h1"],
  cmsEntryImage: ["cmsEntryImage", "img"],
  img: ["img"],
  baseComponentsSocialIcons: ["baseComponentsSocialIcons"],
  componentsLearningLearnings: ["componentsLearningLearnings"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof LayoutPageLayout;
  columns: "div";
  column: "div";
  h1: "h1";
  cmsEntryImage: typeof CmsRowImage;
  img: typeof PlasmicImg__;
  baseComponentsSocialIcons: typeof BaseComponentsSocialIcons;
  componentsLearningLearnings: typeof ComponentsLearningLearnings;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutAuthorAuthor__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutAuthorAuthor__VariantsArgs;
    args?: PlasmicAboutAuthorAuthor__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutAuthorAuthor__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAboutAuthorAuthor__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutAuthorAuthor__ArgProps,
          internalVariantPropNames: PlasmicAboutAuthorAuthor__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutAuthorAuthor__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutAuthorAuthor";
  } else {
    func.displayName = `PlasmicAboutAuthorAuthor.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutAuthorAuthor = Object.assign(
  // Top-level PlasmicAboutAuthorAuthor renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    column: makeNodeComponent("column"),
    h1: makeNodeComponent("h1"),
    cmsEntryImage: makeNodeComponent("cmsEntryImage"),
    img: makeNodeComponent("img"),
    baseComponentsSocialIcons: makeNodeComponent("baseComponentsSocialIcons"),
    componentsLearningLearnings: makeNodeComponent(
      "componentsLearningLearnings"
    ),

    // Metadata about props expected for PlasmicAboutAuthorAuthor
    internalVariantProps: PlasmicAboutAuthorAuthor__VariantProps,
    internalArgProps: PlasmicAboutAuthorAuthor__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutAuthorAuthor;
/* prettier-ignore-end */
