// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wboNivZUXwuALwWQq1HqWe
// Component: vV0rS8SjXr0F

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ComponentsPathwayOfferingItem from "../../ComponentsPathwayOfferingItem"; // plasmic-import: kAApz3d90Dx6/component
import BaseComponentsListItem from "../../BaseComponentsListItem"; // plasmic-import: 5qvnFuh0N1V_/component
import BaseComponentsButton from "../../BaseComponentsButton"; // plasmic-import: Jmnl_p0DOnfd/component
import ComponentsLearningLearningGrid from "../../ComponentsLearningLearningGrid"; // plasmic-import: D6Ikb81zwaMg/component

import {
  ThemeValue,
  useTheme
} from "../17_sds_foundation_global/PlasmicGlobalVariant__Theme"; // plasmic-import: yBTVTgAz2Co9/globalVariant
import { useScreenVariants as useScreenVariantsjuWiTdOksfiv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: JUWiTdOksfiv/globalVariant
import { useScreenVariants as useScreenVariantsohEUf6Jd0EV8 } from "../17_sds_foundation_global/PlasmicGlobalVariant__Screen"; // plasmic-import: OhEUf6Jd0eV8/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_17_sds_foundation_global_css from "../17_sds_foundation_global/plasmic.module.css"; // plasmic-import: 3BHMWCYAenCmWb8ThbnzeF/projectcss
import plasmic_17_sds_foundation_system_css from "../17_sds_foundation_system/plasmic.module.css"; // plasmic-import: dNqcW7FYVqnkjtbdVGjyS8/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wboNivZUXwuALwWQq1HqWe/projectcss
import sty from "./PlasmicSectionsOfferings.module.css"; // plasmic-import: vV0rS8SjXr0F/css

import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: o4rUs5FJlNGU/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 24mFtLAbdat_/icon
import FaAngleRightSvgIcon from "./icons/PlasmicIcon__FaAngleRightSvg"; // plasmic-import: aMDf9tkWGyuE/icon

createPlasmicElementProxy;

export type PlasmicSectionsOfferings__VariantMembers = {};
export type PlasmicSectionsOfferings__VariantsArgs = {};
type VariantPropType = keyof PlasmicSectionsOfferings__VariantsArgs;
export const PlasmicSectionsOfferings__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSectionsOfferings__ArgsType = {};
type ArgPropType = keyof PlasmicSectionsOfferings__ArgsType;
export const PlasmicSectionsOfferings__ArgProps = new Array<ArgPropType>();

export type PlasmicSectionsOfferings__OverridesType = {
  root?: Flex__<"div">;
  column?: Flex__<"div">;
  h2?: Flex__<"h2">;
  upskillChallenges?: Flex__<typeof ComponentsPathwayOfferingItem>;
  hackALongs?: Flex__<typeof ComponentsPathwayOfferingItem>;
  captureTheFlag?: Flex__<typeof ComponentsPathwayOfferingItem>;
};

export interface DefaultSectionsOfferingsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSectionsOfferings__RenderFunc(props: {
  variants: PlasmicSectionsOfferings__VariantsArgs;
  args: PlasmicSectionsOfferings__ArgsType;
  overrides: PlasmicSectionsOfferings__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme(),
    screen: useScreenVariantsjuWiTdOksfiv(),
    screen: useScreenVariantsohEUf6Jd0EV8()
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_17_sds_foundation_global_css.plasmic_tokens,
        plasmic_17_sds_foundation_system_css.plasmic_tokens,
        sty.root,
        {
          [plasmic_17_sds_foundation_global_css.global_theme_darkGrayscale]:
            hasVariant(globalVariants, "theme", "darkGrayscale"),
          [plasmic_17_sds_foundation_global_css.global_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [plasmic_17_sds_foundation_global_css.global_theme_grayscale]:
            hasVariant(globalVariants, "theme", "grayscale"),
          [sty.rootglobal_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          )
        }
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"column"}
        data-plasmic-override={overrides.column}
        hasGap={true}
        className={classNames(projectcss.all, sty.column, {
          [sty.columnglobal_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          )
        })}
      >
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2,
            {
              [sty.h2global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            }
          )}
        >
          {"Lets Hack some things"}
        </h2>
        <div
          className={classNames(projectcss.all, sty.freeBox__jl3Jz, {
            [sty.freeBoxglobal_theme_dark__jl3JZe6UCs]: hasVariant(
              globalVariants,
              "theme",
              "dark"
            )
          })}
        >
          <ComponentsPathwayOfferingItem
            data-plasmic-name={"upskillChallenges"}
            data-plasmic-override={overrides.upskillChallenges}
            actionSlot={
              <BaseComponentsButton
                className={classNames(
                  "__wab_instance",
                  sty.baseComponentsButton__zaOvL
                )}
                color={"secondary"}
                end={
                  <FaAngleRightSvgIcon
                    className={classNames(projectcss.all, sty.svg__rj9Q)}
                    role={"img"}
                  />
                }
                iconEnd={true}
                kind={["fill"]}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___57F84
                    )}
                  >
                    {"See all UCs"}
                  </div>
                }
                onClick={async event => {
                  const $steps = {};

                  $steps["goToUpskillChallenge"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToUpskillChallenge"] != null &&
                    typeof $steps["goToUpskillChallenge"] === "object" &&
                    typeof $steps["goToUpskillChallenge"].then === "function"
                  ) {
                    $steps["goToUpskillChallenge"] = await $steps[
                      "goToUpskillChallenge"
                    ];
                  }
                }}
              />
            }
            centered={true}
            className={classNames("__wab_instance", sty.upskillChallenges, {
              [sty.upskillChallengesglobal_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })}
            imageSlot={
              <React.Fragment>
                <ComponentsLearningLearningGrid
                  className={classNames(
                    "__wab_instance",
                    sty.componentsLearningLearningGrid__yeG1Z
                  )}
                />

                <ComponentsLearningLearningGrid
                  className={classNames(
                    "__wab_instance",
                    sty.componentsLearningLearningGrid__bpDi
                  )}
                  unnamedGroupOfVariants={"_1"}
                />
              </React.Fragment>
            }
            offeringListSlot={
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___9HxBe)}
              >
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__m6L7N
                  )}
                  reverse={true}
                >
                  {"UCs are bite-sized training lessons"}
                </BaseComponentsListItem>
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__qsd70
                  )}
                  reverse={true}
                >
                  {"Only 10 - 30 minutes of student time"}
                </BaseComponentsListItem>
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__qvSvm
                  )}
                  reverse={true}
                >
                  {"Quiz to check understanding"}
                </BaseComponentsListItem>
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__iwQc7,
                    {
                      [sty.baseComponentsListItemglobal_theme_dark__iwQc7E6UCs]:
                        hasVariant(globalVariants, "theme", "dark")
                    }
                  )}
                  reverse={true}
                >
                  {"Completely free"}
                </BaseComponentsListItem>
              </Stack__>
            }
            reverse={true}
          />

          <ComponentsPathwayOfferingItem
            data-plasmic-name={"hackALongs"}
            data-plasmic-override={overrides.hackALongs}
            actionSlot={
              <BaseComponentsButton
                className={classNames(
                  "__wab_instance",
                  sty.baseComponentsButton___6Y3J0
                )}
                color={"secondary"}
                end={
                  <FaAngleRightSvgIcon
                    className={classNames(projectcss.all, sty.svg__dz4R8)}
                    role={"img"}
                  />
                }
                iconEnd={true}
                kind={["fill"]}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hpIe7
                    )}
                  >
                    {"See all HACs"}
                  </div>
                }
                onClick={async event => {
                  const $steps = {};

                  $steps["goToHackALongChallenges"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToHackALongChallenges"] != null &&
                    typeof $steps["goToHackALongChallenges"] === "object" &&
                    typeof $steps["goToHackALongChallenges"].then === "function"
                  ) {
                    $steps["goToHackALongChallenges"] = await $steps[
                      "goToHackALongChallenges"
                    ];
                  }
                }}
              />
            }
            centered={true}
            className={classNames("__wab_instance", sty.hackALongs, {
              [sty.hackALongsglobal_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })}
            headingSlot={"Hack Alongs"}
            imageSlot={
              <React.Fragment>
                <ComponentsLearningLearningGrid
                  className={classNames(
                    "__wab_instance",
                    sty.componentsLearningLearningGrid___73QXt
                  )}
                  slot1={"data-recovery-basics"}
                  slot2={"geoint-challenge-1"}
                  slot3={"intro-dynamic-analysis"}
                  unnamedGroupOfVariants={
                    hasVariant(globalVariants, "screen", "large") ? "_1" : "_3"
                  }
                />

                <ComponentsLearningLearningGrid
                  className={classNames(
                    "__wab_instance",
                    sty.componentsLearningLearningGrid__btB9N
                  )}
                  slot1={"data-recovery-basics"}
                  slot2={"geoint-challenge-1"}
                  slot3={"intro-dynamic-analysis"}
                  unnamedGroupOfVariants={"_1"}
                />
              </React.Fragment>
            }
            offeringListSlot={
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uw1L2, {
                  [sty.freeBoxglobal_theme_dark__uw1L2E6UCs]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__uYxWb,
                    {
                      [sty.baseComponentsListItemglobal_theme_dark__uYxWbe6UCs]:
                        hasVariant(globalVariants, "theme", "dark")
                    }
                  )}
                  reverse={
                    hasVariant(globalVariants, "screen", "medium")
                      ? true
                      : undefined
                  }
                >
                  {"HALs accompany free videos"}
                </BaseComponentsListItem>
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__unzmo,
                    {
                      [sty.baseComponentsListItemglobal_theme_dark__unzmoe6UCs]:
                        hasVariant(globalVariants, "theme", "dark")
                    }
                  )}
                  reverse={
                    hasVariant(globalVariants, "screen", "medium")
                      ? true
                      : undefined
                  }
                >
                  {"About 2 hours of student time"}
                </BaseComponentsListItem>
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__wPgLi
                  )}
                  reverse={
                    hasVariant(globalVariants, "screen", "medium")
                      ? true
                      : undefined
                  }
                >
                  {"Full virtual lab environments"}
                </BaseComponentsListItem>
                <BaseComponentsListItem
                  className={classNames(
                    "__wab_instance",
                    sty.baseComponentsListItem__pi3K
                  )}
                  reverse={
                    hasVariant(globalVariants, "screen", "medium")
                      ? true
                      : undefined
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d6Qsa,
                      {
                        [sty.textglobal_theme_dark__d6Qsae6UCs]: hasVariant(
                          globalVariants,
                          "theme",
                          "dark"
                        )
                      }
                    )}
                  >
                    {"Step-by-step instructions & screenshots"}
                  </div>
                </BaseComponentsListItem>
              </Stack__>
            }
          />

          <ComponentsPathwayOfferingItem
            data-plasmic-name={"captureTheFlag"}
            data-plasmic-override={overrides.captureTheFlag}
            actionSlot={
              <BaseComponentsButton
                className={classNames(
                  "__wab_instance",
                  sty.baseComponentsButton__okR1S
                )}
                color={"secondary"}
                end={
                  <FaAngleRightSvgIcon
                    className={classNames(projectcss.all, sty.svg__fD6RO)}
                    role={"img"}
                  />
                }
                iconEnd={true}
                kind={["fill"]}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qreXg
                    )}
                  >
                    {"See all CTFs"}
                  </div>
                }
                onClick={async event => {
                  const $steps = {};

                  $steps["goToCaptureTheFlag"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToCaptureTheFlag"] != null &&
                    typeof $steps["goToCaptureTheFlag"] === "object" &&
                    typeof $steps["goToCaptureTheFlag"].then === "function"
                  ) {
                    $steps["goToCaptureTheFlag"] = await $steps[
                      "goToCaptureTheFlag"
                    ];
                  }
                }}
              />
            }
            centered={true}
            className={classNames("__wab_instance", sty.captureTheFlag)}
            headingSlot={"Capture the Flags"}
            imageSlot={
              <React.Fragment>
                <ComponentsLearningLearningGrid
                  className={classNames(
                    "__wab_instance",
                    sty.componentsLearningLearningGrid__yAdl5
                  )}
                  slot1={"nahamcon-2024"}
                  slot2={"nahamcon-2024"}
                  slot3={"snyk-fetch-the-flag-2023"}
                  slot4={"snyk-fetch-the-flag-2023"}
                  slot5={"snyk-fetch-the-flag-2023"}
                  unnamedGroupOfVariants={
                    hasVariant(globalVariants, "screen", "large") ? "_1" : "_2"
                  }
                />

                <ComponentsLearningLearningGrid
                  className={classNames(
                    "__wab_instance",
                    sty.componentsLearningLearningGrid__aczna
                  )}
                  slot1={"nahamcon-2024"}
                  slot2={"nahamcon-2024"}
                  slot3={"snyk-fetch-the-flag-2023"}
                  slot4={"snyk-fetch-the-flag-2023"}
                  slot5={"snyk-fetch-the-flag-2023"}
                  unnamedGroupOfVariants={
                    hasVariant(globalVariants, "screen", "large") ? "_1" : "_1"
                  }
                />
              </React.Fragment>
            }
            offeringListSlot={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5DQMo
                )}
              >
                {
                  "Missed an event where the Just Hacking Training Team delivered a killer Capture the Flag competition? Didn't have enough time to just roam or try other approaches?\n\nWorry no more!\n\nContinue playing to your heart's content. Only difference is that there\u2019s no time limits and no scoreboard. Learn with no pressure!"
                }
              </div>
            }
            reverse={true}
          />
        </div>
      </Stack__>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "column",
    "h2",
    "upskillChallenges",
    "hackALongs",
    "captureTheFlag"
  ],
  column: ["column", "h2", "upskillChallenges", "hackALongs", "captureTheFlag"],
  h2: ["h2"],
  upskillChallenges: ["upskillChallenges"],
  hackALongs: ["hackALongs"],
  captureTheFlag: ["captureTheFlag"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  column: "div";
  h2: "h2";
  upskillChallenges: typeof ComponentsPathwayOfferingItem;
  hackALongs: typeof ComponentsPathwayOfferingItem;
  captureTheFlag: typeof ComponentsPathwayOfferingItem;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSectionsOfferings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSectionsOfferings__VariantsArgs;
    args?: PlasmicSectionsOfferings__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSectionsOfferings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSectionsOfferings__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSectionsOfferings__ArgProps,
          internalVariantPropNames: PlasmicSectionsOfferings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionsOfferings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionsOfferings";
  } else {
    func.displayName = `PlasmicSectionsOfferings.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionsOfferings = Object.assign(
  // Top-level PlasmicSectionsOfferings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    column: makeNodeComponent("column"),
    h2: makeNodeComponent("h2"),
    upskillChallenges: makeNodeComponent("upskillChallenges"),
    hackALongs: makeNodeComponent("hackALongs"),
    captureTheFlag: makeNodeComponent("captureTheFlag"),

    // Metadata about props expected for PlasmicSectionsOfferings
    internalVariantProps: PlasmicSectionsOfferings__VariantProps,
    internalArgProps: PlasmicSectionsOfferings__ArgProps
  }
);

export default PlasmicSectionsOfferings;
/* prettier-ignore-end */
